name: Check File Size
on: # or directly `on: [push]` to run the action on every push on any branch
    push:
        branches: [main]

    # to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    sync-to-hub:
        runs-on: ubuntu-latest
        steps:
            - name: Check large files
              uses: ActionsDesk/lfs-warning@v3.2
              with:
                  filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces
